# Q-1

In [38]:
import numpy as np
import pandas as pd
from scipy import stats

In [39]:
score=np.random.randint(40,101,50)
score

array([ 97,  45,  78,  90,  84,  91,  70,  83,  52,  65, 100,  73,  60,
        73,  93,  73,  63,  56,  95,  67,  92,  43,  60,  79,  52,  84,
        91,  42,  53, 100,  98,  55,  78,  84,  74,  98,  68,  43,  84,
        66,  55,  53,  61,  53,  63,  58,  84,  56,  58,  48], dtype=int32)

In [40]:
samp_mean=np.mean(score)
samp_std=np.std(score,ddof=1)
print(f'mean:{samp_mean}')
print(f'std:{samp_std:.2f}')

mean:70.82
std:17.39


In [41]:
c_interval=stats.t.interval(confidence=0.95,
df=len(score)-1,loc=samp_mean,
scale=samp_std/np.sqrt(len(score)))

print(f'confidence interval:{c_interval}')
print(f"we are 95% confident that the true mean falls within {c_interval}")

confidence interval:(np.float64(65.87861935050091), np.float64(75.76138064949907))
we are 95% confident that the true mean falls within (np.float64(65.87861935050091), np.float64(75.76138064949907))


In [42]:
score=np.random.randint(40,101,500)
score

array([ 91,  40,  59,  77,  64,  41,  85,  90,  65,  63,  78,  54,  84,
        62,  59,  72,  65,  82,  95,  93,  64,  49,  47,  84,  56,  97,
        52,  82,  54,  58,  97,  92,  88,  61,  89,  72,  43,  42,  55,
        65,  57, 100,  69,  83,  40,  49,  40,  94,  63,  79,  73,  78,
        84,  81,  47,  54,  97,  69,  45,  68,  81,  46,  65,  84,  95,
        47,  58,  41,  98,  58,  68,  53,  61,  68,  76,  93,  65,  71,
        42,  68,  63,  77,  74,  95,  86,  92,  83,  89,  42,  68,  43,
        99,  82,  84,  82,  44,  85,  59,  81,  96,  93,  82,  43,  79,
        95,  71,  75,  76,  52,  79,  54,  93,  48,  73,  65,  86,  56,
        62,  46,  90,  72,  70,  70,  54,  64,  75,  95,  99,  66,  84,
        60,  78,  91,  78,  70,  48,  56,  57,  78,  56,  67,  52,  45,
        88,  49,  56,  87,  41,  53,  75,  52,  94,  91,  85,  51,  86,
        41,  66,  94,  63,  79,  46,  85,  69,  53,  96,  68,  71,  73,
        41,  65,  54,  85,  76,  63,  82,  53,  68,  44,  99,  7

In [43]:
samp_mean=np.mean(score)
samp_std=np.std(score,ddof=1)
print(f'mean:{mean}')
print(f'std:{std:.2f}')

NameError: name 'mean' is not defined

In [ ]:
c_interval=stats.t.interval(confidence=0.95,
df=len(score)-1,loc=samp_mean,
scale=samp_std/np.sqrt(len(score)))

print(f'confidence interval:{c_interval}')
print(f"we are 95% confident that the true mean falls within {c_interval}")

confidence interval:(np.float64(68.30253489385046), np.float64(71.37746510614954))
we are 95% confident that the true mean falls within (np.float64(68.30253489385046), np.float64(71.37746510614954))


## the difference between the sample size 50 and 500 is in sample size 500 the range become narrow making it more accurate as in sample size 50

# Q-2

In [ ]:
pop_mean=70
pop_std=10
sample=np.random.normal(70,10,100)
samp_mean=np.mean(sample)
alpha=0.05
print(f'sample mean: {samp_mean:.2f}')

sample mean: 70.02


In [ ]:
z_score=(samp_mean-pop_mean)/(pop_std/np.sqrt(len(sample)))
print(f'z_score:{z_score:.2f}')
critical_value=stats.norm.ppf(1-((alpha)/2))
print(f'critical value:{critical_value:.2f}')
p_value=2*(1-stats.norm.cdf(abs(z_score)))
print(f'p-value:{p_value:.2f}')



z_score:0.02
critical value:1.96
p-value:0.98


### null hypothesis is that mean is 70
### alternate hypothesis is that mean is not 70
### two tailed test so alpha=0.05

In [ ]:
if z_score>critical_value or z_score<-critical_value:
    print("reject null hypothesis")
else:
    print("fail to reject null hypothesis")


fail to reject null hypothesis


In [ ]:

if p_value>alpha:
    print("fail to reject null hypothesis")
else:
    print("reject null hypothesis")

fail to reject null hypothesis


In [ ]:
pop_mean=70
pop_std=10
sample=np.random.normal(75,10,100)
samp_mean=np.mean(sample)
alpha=0.05

In [ ]:
z_score=(samp_mean-pop_mean)/(pop_std/np.sqrt(len(sample)))
critical_value=stats.norm.ppf(1-alpha/2)
p_value=2*(1-stats.norm.cdf(abs(z_score)))
print(f'z_score:{z_score:.2f}')
print(f'p-value:{p_value}')
print(f'critical value:{critical_value:.2f}')

z_score:3.71
p-value:0.00020328688671300554
critical value:1.96


In [ ]:
if z_score>critical_value or z_score<-critical_value:
    print("reject null hypothesis")
else:
    print("fail to reject null hypothesis")


reject null hypothesis


In [ ]:
if p_value>alpha:
    print("fail to reject null hypothesis")
else:
    print("reject null hypothesis")
    

reject null hypothesis


# Q-3

In [46]:
samp_weight=np.random.randint(50,91,30)
samp_weight

array([72, 85, 86, 87, 59, 75, 82, 88, 50, 79, 88, 89, 86, 72, 77, 85, 75,
       61, 53, 58, 81, 55, 85, 70, 54, 78, 77, 88, 67, 75], dtype=int32)

In [47]:
pop_mean=70
alpha=0.05

In [48]:
t_stat,p_value=stats.ttest_1samp(samp_weight,pop_mean)
print(f't-statistic: {t_stat:.2f}')
print(f'p-value: {p_value:.4f}')

t-statistic: 2.05
p-value: 0.0491


### null hypothesis is that the population mean is equal to 70
### alternative hypothesis is that the population mean is not equal to 70 so two tailed 

In [49]:
if p_value>alpha:
    print("fail to reject null hypothesis")
else:
    print("reject null hypothesis")

reject null hypothesis
